# Load Data

In [1]:
# load the dataset skipping the first 3 rows
import pandas as pd
data = pd.read_excel('GDP.xls', skiprows = 3)
data

                    Country Name Country Code  ...          2019          2020
0                          Aruba          ABW  ...           NaN           NaN
1    Africa Eastern and Southern          AFE  ...  1.008375e+12  9.188155e+11
2                    Afghanistan          AFG  ...  1.879945e+10  2.011614e+10
3     Africa Western and Central          AFW  ...  7.945725e+11  7.845876e+11
4                         Angola          AGO  ...  8.941719e+10  5.837598e+10
..                           ...          ...  ...           ...           ...
261                       Kosovo          XKX  ...  7.899879e+09  7.716925e+09
262                  Yemen, Rep.          YEM  ...           NaN           NaN
263                 South Africa          ZAF  ...  3.879346e+11  3.354421e+11
264                       Zambia          ZMB  ...  2.330867e+10  1.811063e+10
265                     Zimbabwe          ZWE  ...  1.928429e+10  1.805117e+10

[266 rows x 65 columns]

# Clean Data

In [2]:
# remove aggregated data (eg. World Total, Europe Total, Asia Total, etc.)
codes = ['WLD', 'HIC', 'OED', 'PST', 'IBT', 'ECS', 'LMY', 'MIC', 'IBD', 'EUU', 'EAS', 'NAC', 'UMC',
         'LTE', 'EMU', 'EAR', 'EAP', 'TEA', 'LCN', 'TLA', 'LAC', 'LMC', 'TEC', 'ECA', 'MEA', 'ARB',
         'SAS', 'TSA', 'IDA', 'MNA', 'TMN', 'SSF', 'TSS', 'SSA', 'CEB', 'PRE', 'IDX', 'IDB', 'LDC',
         'FCS', 'HPC', 'SST', 'LIC', 'OSS', 'CSS', 'PSS']        
for code in codes:
  data.drop(data.loc[data['Country Code'] == code].index, inplace = True)
data

                    Country Name Country Code  ...          2019          2020
0                          Aruba          ABW  ...           NaN           NaN
1    Africa Eastern and Southern          AFE  ...  1.008375e+12  9.188155e+11
2                    Afghanistan          AFG  ...  1.879945e+10  2.011614e+10
3     Africa Western and Central          AFW  ...  7.945725e+11  7.845876e+11
4                         Angola          AGO  ...  8.941719e+10  5.837598e+10
..                           ...          ...  ...           ...           ...
261                       Kosovo          XKX  ...  7.899879e+09  7.716925e+09
262                  Yemen, Rep.          YEM  ...           NaN           NaN
263                 South Africa          ZAF  ...  3.879346e+11  3.354421e+11
264                       Zambia          ZMB  ...  2.330867e+10  1.811063e+10
265                     Zimbabwe          ZWE  ...  1.928429e+10  1.805117e+10

[220 rows x 65 columns]

In [3]:
# after removing some rows, the row index will have missing values, reset to consecutive running order
data = data.reset_index(drop = True)

# drop unnecessary columns
data = data.drop(columns = ['Country Code', 'Indicator Name', 'Indicator Code'], axis = 1)
data

                    Country Name          1960  ...          2019          2020
0                          Aruba           NaN  ...           NaN           NaN
1    Africa Eastern and Southern  1.929944e+10  ...  1.008375e+12  9.188155e+11
2                    Afghanistan  5.377778e+08  ...  1.879945e+10  2.011614e+10
3     Africa Western and Central  1.040428e+10  ...  7.945725e+11  7.845876e+11
4                         Angola           NaN  ...  8.941719e+10  5.837598e+10
..                           ...           ...  ...           ...           ...
215                       Kosovo           NaN  ...  7.899879e+09  7.716925e+09
216                  Yemen, Rep.           NaN  ...           NaN           NaN
217                 South Africa  7.575397e+09  ...  3.879346e+11  3.354421e+11
218                       Zambia  7.130000e+08  ...  2.330867e+10  1.811063e+10
219                     Zimbabwe  1.052990e+09  ...  1.928429e+10  1.805117e+10

[220 rows x 62 columns]

In [4]:
# rename column index, so that string '1960' becomes integer 1960
data.columns = ['Name', 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
                1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986,
                1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
                2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
                2015, 2016, 2017, 2018, 2019, 2020]

# Create New Data File

In [5]:
# create new df in a desired format
df = pd.DataFrame({ 'Country':[], 'Year':[], 'GDP':[] })
df['Year'] = df['Year'].astype(int)

# start to read data into the new df
r = data.shape[0]       # 220 rows
c = data.shape[1] - 1   # 61 columns (after minus country name)
for row in range(r):
  for i in range(c):    # 61: 1960 to 2020
   df = pd.concat([df, pd.DataFrame({ 'Country':[data['Name'][row]], 'Year':[1960+i], 'GDP':[data[1960+i][row]] }) ])
df

     Country  Year           GDP
0      Aruba  1960           NaN
0      Aruba  1961           NaN
0      Aruba  1962           NaN
0      Aruba  1963           NaN
0      Aruba  1964           NaN
..       ...   ...           ...
0   Zimbabwe  2016  2.054868e+10
0   Zimbabwe  2017  1.758489e+10
0   Zimbabwe  2018  1.811554e+10
0   Zimbabwe  2019  1.928429e+10
0   Zimbabwe  2020  1.805117e+10

[13420 rows x 3 columns]

In [6]:
# fill null field with zero
df.gdp = df.GDP.fillna(0)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access

     Country  Year           GDP
0      Aruba  1960           NaN
0      Aruba  1961           NaN
0      Aruba  1962           NaN
0      Aruba  1963           NaN
0      Aruba  1964           NaN
..       ...   ...           ...
0   Zimbabwe  2016  2.054868e+10
0   Zimbabwe  2017  1.758489e+10
0   Zimbabwe  2018  1.811554e+10
0   Zimbabwe  2019  1.928429e+10
0   Zimbabwe  2020  1.805117e+10

[13420 rows x 3 columns]

#Save Final Data

In [7]:
# save final data format for creating Tableau dashboard
df.to_excel('World GDP.xlsx', index = False)